### ISSUE TITLE
blueprint generator-jhipster-angular-flex don't works

### ISSUE THREAD

**Issue by FrancescoMez79** [robwalls3/generator-jhipster-angular-flex#1]
Hello,
we are trying to install this blueprint (0.4.0).

we have updated the version of Jhipster to 6.10.5 :
https://i.imgur.com/6CSIb3M.png

and then, install the blueprint, with the command:
npm install -g generator-jhipster-angular-flex

After that, we have sent this command :
jhipster --blueprint angular-flex

and we receive this error :
The installed generator-jhipster-angular-flex blueprint targets JHipster v^6.10.5 and is not compatible with this JHipster version.

How is it possible?

Thanks,
Francesco

These are the logs :
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-angular-flex at /home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster-angular-flex
INFO! No custom commands found within blueprint: generator-jhipster-angular-flex at /home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster-angular-flex
INFO! Executing jhipster:app
WARNING! --blueprint option is deprecated. Please use --blueprints instead

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.10.5
Application files will be generated in folder: /home/eminds/eclipse/flexblueprint
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

ERROR! The installed generator-jhipster-angular-flex blueprint targets JHipster v^6.10.5 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
Error: The installed generator-jhipster-angular-flex blueprint targets JHipster v^6.10.5 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
    at module.exports.error (/home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/generators/generator-base.js:1590:15)
    at module.exports.checkJHipsterBlueprintVersion (/home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/generators/generator-base-private.js:919:22)
    at blueprints.forEach.blueprint (/home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/generators/app/index.js:266:30)
    at Array.forEach (<anonymous>)
    at module.exports.validateBlueprint (/home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/generators/app/index.js:265:37)
    at Object.<anonymous> (/home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:976:25)
    at /home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:26:19
    at runLoop.add.continueQueue (/home/eminds/.nvm/versions/node/v10.22.1/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:977:11)
eminds@eminds-VirtualBox:~/eclipse/flexblueprint$

**Comment by FrancescoMez79** [comment]
Hello,
any news?

Thanks,
Francesco
